### ISSUE TITLE
ST7789 with 8-bit Parallel I/F

### ISSUE THREAD

**Issue by Boyeen** [dejwk/roo_display#5]
I'm intrigued by the new TTGO T-Display-S3 with 1.9" IPS. It uses an ST7789 but via an 8-bit parallel i/f.
Any idea of supporting this?  Even TFT_eSPI doesn't, but LilyGo has patched the lib. I think this will be a very popular board going forward. I have a display on order from China and will be happy to help any way I can.

Tim

AliExpress [link](https://www.aliexpress.com/item/3256804433836811.html?spm=a2g0o.productlist.0.0.10b4696dBlBCZp&algo_pvid=cd892352-95e2-4936-9f97-63f5c2d70b92&algo_exp_id=cd892352-95e2-4936-9f97-63f5c2d70b92-1&pdp_ext_f=%7B%22sku_id%22%3A%2212000029861111437%22%7D&pdp_npi=2%40dis%21USD%2124.65%2116.27%21%21%21%21%21%402101d4a716623440679514894e987f%2112000029861111437%21sea&curPageLogUid=70xL124hGm71)

**Comment by Boyeen** [comment]
Just checking if you have seen this?

**Comment by dejwk** [comment]
Hi Boyeen, I am so sorry that I missed this comment before.

I have not yet looked into parallel drivers. Generally, I believe it is very possible to add them and these experiments are on my list.

Meanwhile, I am now working on preparing this lib for a release. I added a bunch of features, including a pass-thru driver that can use TFT_eSPI.

Did you make any progress on that driver you mention? I noticed that you forked TFT_eSPI. I would be quite interested in merging any new drivers into my library :)

**Comment by Boyeen** [comment]
Hi,Sadly no, I wouldn’t know how to go about a parallel driver. When you do get around to trying it out I will be delighted to help with testing or anything you can set me to.I DID come up with  the config settings for the new 1.69” 240x280 displays (you see them from China with the rounded corners and I think more accurate colors). I will update my fork and send you a pull request.Sent from my iPadOn Mar 19, 2023, at 5:07 PM, dejwk ***@***.***> wrote:﻿
Hi Boyeen, I am so sorry that I missed this comment before.
I have not yet looked into parallel drivers. Generally, I believe it is very possible to add them and these experiments are on my list.
Meanwhile, I am now working on preparing this lib for a release. I added a bunch of features, including a pass-thru driver that can use TFT_eSPI.
Did you make any progress on that driver you mention? I noticed that you forked TFT_eSPI. I would be quite interested in merging any new drivers into my library :)

**Comment by dejwk** [comment]
Sounds good!

Interesting device, I might give it a try. Did you come across any open-source drivers for it at all?

**Comment by Boyeen** [comment]
Do you mean open source drivers for the 8-bit parallel display? None, only TFT-eSPI which LilyGo modified. 

BTW that display is super fast to update (8 bit parallel so I know it's obviously faster) but it really is amazing to be able to get the frame-rate you do from an ESP32.... I'm really hoping you can support it in RooDisplay because this is my favorite display driver now :-)

**Comment by dejwk** [comment]
I have recently implemented an adapter driver that allows to use roo_display on top the TFT_eSPI drivers. So if you have a driver for your thing that works with TFT_eSPI, you may want to give it a try. The performance should be good; the driver only uses setAddr, writePixels and fillPixels which tend to be well-optimized in TFT_eSPI. 

You will find the adapter in the driver/ directory, with some comments on how to use it.

FWiW, I also added native support for JPEG and PNG, and some other features - and I am in the process of documenting all that in the README.

I am interested in increasing driver support, though, and I am curious about parallel drivers. I think these 'combo' devices that do not require you for actually put in all the wires, are really interesting.

The first combo I tried so far, for which there is already a driver in roo_display, is the ILI9488-based Makerfabs device. It has a very good quality touch panel (capacitive), blowing any XPT2046 out of the water. It is still SPI, though.

I ordered the thing you mentioned. It will be an interesting form factor to support.

**Comment by dejwk** [comment]
Hi Boyeen, good news! I god the T-Display-S3 a couple of days ago, and I just finished writing the driver for it. Give it a shot and let me know!

basic setup:

```
#include "roo_display/products/lilygo/t_display_s3.h"

// ...

using namespace roo_display;

products::lilygo::TDisplayS3 tft(Orientation().rotateLeft());
Display display(tft);


void setup() {
  // ...
  tft.initTransport();
  display.init(color::White);
}

```

**Comment by Boyeen** [comment]
I was working, then got sick and was out for a month. Now I get a compile error:
In roo_display.h:208  products::lilygo::TDisplayS3 has no member named “extents”

I installed the latest version
