### ISSUE TITLE
ESP32-S3

### ISSUE THREAD

**Issue by Boyeen** [dejwk/roo_display#6]
Hiya,
Sorry for delay testing the new driver, I am out sick.

So far no joy but I will keep looking when I can. 

Latest error:
.pio/libdeps/esp32dev/roo_display/roo_display/products/lilygo/t_display_s3.h:40:31: error: 'esp32s3' was not declared in this scope
   roo_display::St7789_Generic<esp32s3::ParallelLcd8Bit, 170, 320, 35, 0, 35, 0>

Could it be related to. CONFIG_IDF_TARGET_ESP32S3

**Comment by dejwk** [comment]
I think this must be because this file doesn't see the macro definitions for ESP32S3:

**Comment by Boyeen** [comment]
Yeah, user error, you are 100% correct. I apologize....

It works and is super fast... I'll keep testing.

Nice job
