### ISSUE TITLE
New compile error For T-Display S3

### ISSUE THREAD

**Issue by Boyeen** [dejwk/roo_display#7]
I was out sick and travelling for a month… back to testing again, updated to latest library and now I see a compile error:

roo_display.h:208  is expecting member “extents” which is not in products::lillygo::TDisplayS3

**Comment by dejwk** [comment]
Could you share your sketch? I couldn't reproduce.

Is it possible that you're trying to create the DrawingContext using the 'device' instead of the 'display'?

**Comment by Boyeen** [comment]
Yeah, You were right, in a single place I set the DrawingContext wrong and that was the issue. Thanks again.
