### ISSUE TITLE
Missing functions in roo_display::esp32s3::ParallelLcd8Bit'

### ISSUE THREAD

**Issue by Boyeen** [dejwk/roo_display#9]
Trying to compile the current lib for the TTGO_T-DISPLAY_S3 I get a number of missing transport method declarations in parallel_lcd_8bit.h

beginWriteOnlyTransaction()
sync()
write_XXX_async() etc.

**Comment by dejwk** [comment]
Sorry about that. I broke it when I introduced the latest round of performance optimizations for SPI-based displays.

I believe I fixed it now, although at the moment I can't verify on the actual device (I am travelling).

**Comment by Boyeen** [comment]
No problem, thanks for looking into it while away (hopefully somewhere nice :-)
I just tested with the latest version and it seems to work fine again.

Thanks
